#!/bin/bash
./maketree.sh /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/mafft-nexus-internal-trimmed-gblocks-clean-75p-raxml /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/data/astral_out_ge122/cp_con_all_contree_BootstrapCollapsed.nwk astral_topo_ge122_75p
./maketree.sh /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/mafft-nexus-internal-trimmed-gblocks-clean-75p-raxml /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/data/astral_out_ge147/cp_con_all_contree_BootstrapCollapsed.nwk astral_topo_ge147_75p
./maketree.sh /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/mafft-nexus-internal-trimmed-gblocks-clean-75p-raxml /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/data/astral_out_ge16/cp_con_all_contree_BootstrapCollapsed.nwk astral_topo_ge16_75p
./maketree.sh /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/mafft-nexus-internal-trimmed-gblocks-clean-75p-raxml /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/data/astral_out_ge41_old/cp_con_all_contree_BootstrapCollapsed.nwk astral_topo_ge41_75p
./maketree.sh /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/mafft-nexus-internal-trimmed-gblocks-clean-75p-raxml /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/data/astral_out_ge82/cp_con_all_contree_BootstrapCollapsed.nwk astral_topo_ge82_75p

./maketree.sh /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/mafft-nexus-internal-trimmed-gblocks-clean-90p-raxml /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/data/astral_out_ge122/cp_con_all_contree_BootstrapCollapsed.nwk astral_topo_ge122_90p
./maketree.sh /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/mafft-nexus-internal-trimmed-gblocks-clean-90p-raxml /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/data/astral_out_ge147/cp_con_all_contree_BootstrapCollapsed.nwk astral_topo_ge147_90p
./maketree.sh /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/mafft-nexus-internal-trimmed-gblocks-clean-90p-raxml /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/data/astral_out_ge16/cp_con_all_contree_BootstrapCollapsed.nwk astral_topo_ge16_90p
./maketree.sh /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/mafft-nexus-internal-trimmed-gblocks-clean-90p-raxml /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/data/astral_out_ge41_old/cp_con_all_contree_BootstrapCollapsed.nwk astral_topo_ge41_90p
./maketree.sh /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/mafft-nexus-internal-trimmed-gblocks-clean-90p-raxml /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/data/astral_out_ge82/cp_con_all_contree_BootstrapCollapsed.nwk astral_topo_ge82_90p

./maketree.sh /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/mafft-nexus-internal-trimmed-gblocks-clean-95p-raxml /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/data/astral_out_ge122/cp_con_all_contree_BootstrapCollapsed.nwk astral_topo_ge122_95p
./maketree.sh /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/mafft-nexus-internal-trimmed-gblocks-clean-95p-raxml /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/data/astral_out_ge147/cp_con_all_contree_BootstrapCollapsed.nwk astral_topo_ge147_95p
./maketree.sh /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/mafft-nexus-internal-trimmed-gblocks-clean-95p-raxml /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/data/astral_out_ge16/cp_con_all_contree_BootstrapCollapsed.nwk astral_topo_ge16_95p
./maketree.sh /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/mafft-nexus-internal-trimmed-gblocks-clean-95p-raxml /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/data/astral_out_ge41_old/cp_con_all_contree_BootstrapCollapsed.nwk astral_topo_ge41_95p
./maketree.sh /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/mafft-nexus-internal-trimmed-gblocks-clean-95p-raxml /home/projects/ku_00039/people/zelili/GAGA/taxon-sets/all/data/astral_out_ge82/cp_con_all_contree_BootstrapCollapsed.nwk astral_topo_ge82_95p

